
package com.ncjk.ticp.ticp.wgb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.ncjk.utcs.common.servlet.SpringUtil;
import com.ncjk.utcs.common.webservice.client.LoginCommandImpl;
import com.ncjk.utcs.common.webservice.client.interfaces.LoginCommand;
import org.apache.cxf.jaxws.endpoint.dynamic.JaxWsDynamicClientFactory;
import org.apache.log4j.Logger;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Resource;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-12-19T16:53:31.942+08:00
 * Generated source version: 2.7.18
 * 
 */
public class IGBTICPJK_GBTICPJKImplPort_Client {

    public IGBTICPJK_GBTICPJKImplPort_Client() throws MalformedURLException {
       LoginCommand loginCommand = (LoginCommand)SpringUtil.getApplicationContext().getBean("loginCommand",LoginCommand.class);
        loginCommand.Login();
    }

    public static void main(String[] args) throws Exception {
        //这个是用cxf 客户端访问cxf部署的webservice服务
        //千万记住，访问cxf的webservice必须加上namespace ,否则通不过
        //现在又另外一个问题，传递过去的参数服务端接收不到
        JaxWsDynamicClientFactory dcf = JaxWsDynamicClientFactory.newInstance();
        org.apache.cxf.endpoint.Client client = dcf.createClient("http://192.168.1.52:8080/TICPCentral/gbTICPJK?wsdl");
        //url为调用webService的wsdl地址
        QName name=new QName("http://wgb.ticp.ticp.ncjk.com/","gbTICPJK");
        //namespace是命名空间，methodName是方法名
        String xmlStr = "<?xml version='1.0' encoding='UTF-8'?><Message><Version>1.0</Version><Token/><From><Address><Sys>UTCS</Sys><SubSys/><Instance/></Address></From><To><Address><Sys>TICP</Sys><SubSys/><Instance/></Address></To><Type>REQUEST</Type><Seq>20161219141840000001</Seq><Body><Operation order='1' name='Login'><SDO_User><UserName>Admin</UserName><Pwd>12345</Pwd></SDO_User></Operation></Body></Message>";
        //paramvalue为参数值
        Object[] objects=client.invoke(name,xmlStr);
        //调用web Service//输出调用结果
        System.out.println(objects[0].toString());
    }
}
