package com.ncjk.ticp.ticp.wgb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-12-19T16:53:32.084+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://wgb.ticp.ticp.ncjk.com/", name = "IGBTICPJK")
@XmlSeeAlso({ObjectFactory.class})
public interface IGBTICPJK {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sonTicpCommon", targetNamespace = "http://wgb.ticp.ticp.ncjk.com/", className = "com.ncjk.ticp.ticp.wgb.SonTicpCommon")
    @WebMethod
    @ResponseWrapper(localName = "sonTicpCommonResponse", targetNamespace = "http://wgb.ticp.ticp.ncjk.com/", className = "com.ncjk.ticp.ticp.wgb.SonTicpCommonResponse")
    public java.lang.String sonTicpCommon(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
