
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ncjk.ticp.ticp.wgb;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-12-19T16:53:31.995+08:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "gbTICPJK",
                      portName = "GBTICPJKImplPort",
                      targetNamespace = "http://wgb.ticp.ticp.ncjk.com/",
                      endpointInterface = "com.ncjk.ticp.ticp.wgb.IGBTICPJK")
                      
public class IGBTICPJKImpl implements IGBTICPJK {

    private static final Logger LOG = Logger.getLogger(IGBTICPJKImpl.class.getName());

    /* (non-Javadoc)
     * @see com.ncjk.ticp.ticp.wgb.IGBTICPJK#sonTicpCommon(java.lang.String  arg0 )*
     */
    public java.lang.String sonTicpCommon(java.lang.String arg0) { 
        LOG.info("Executing operation sonTicpCommon");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
