package com.ncjk.ticp.ticp.wgb;

import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.DocumentHelper;
import org.dom4j.Element;
import org.dom4j.io.OutputFormat;
import org.dom4j.io.XMLWriter;

import java.io.IOException;
import java.io.StringWriter;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-12-19T16:53:32.107+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "gbTICPJK",
                  targetNamespace = "http://wgb.ticp.ticp.ncjk.com/") 
public class GbTICPJK extends Service {

    public final static QName GBTICPJKImplPort = new QName("http://wgb.ticp.ticp.ncjk.com/", "GBTICPJKImplPort");

    public GbTICPJK(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    /**
     *
     * @return
     *     returns IGBTICPJK
     */
    @WebEndpoint(name = "GBTICPJKImplPort")
    public IGBTICPJK getGBTICPJKImplPort() {
        return super.getPort(GBTICPJKImplPort, IGBTICPJK.class);
    }


}
